name:        icp-forecast
version:     0.0.1
license:     BSD3
author:      John Wiegley
maintainer:  john@dfinity.org
description: A forecaster for ICP token holders.

ghc-options:
   - -Wall
   - -Wno-missing-home-modules
   - -fno-ignore-asserts

dependencies:
  - base >= 4.5 && < 5.0
  - bytestring
  - containers
  - hedgehog
  - mtl
  - simple-amount
  - pretty-show

library:
  source-dirs: src
  exposed-modules:
    - Staking

executables:
  icp-forecast:
    main: Main.hs
    dependencies:
      - icp-forecast
